Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -101,24 +101,29 @@ jobs:
             automake
           sudo apt-get update
           sudo apt-get upgrade
+          
       - name: Find and Update configure.ac or configure.in
         run: |
           files=$(find . -name 'configure.ac' -o -name 'configure.in')
           if [ -n "$files" ]; then
             echo "Running autoupdate on the following files:"
             echo "$files"
-            autoupdate -f $files
+            autoupdate -f $files || { echo 'Autoupdate failed' ; exit 1; }
           else
             echo "No configure.ac or configure.in files found."
           fi
           
-      - name: Commit changes
+      - name: Commit changes if any
         run: |
-          git config --global user.name "qarrobin-djuti"
-          git config --global user.email "qarrobin.djuti@gmail.com"
-          git add .
-          git commit -m 'Run autoupdate'
-          git push || echo "No changes to commit"
+          if [ -n "$(git status --porcelain)" ]; then
+            git config --global user.name "qarrobin-djuti"
+            git config --global user.email "qarrobin.djuti@gmail.com"
+            git add .
+            git commit -m 'Run autoupdate'
+            git push
+          else
+            echo "No changes to commit"
+          fi
       # Set up Java 17 required by Gradle
       - name: Setup Java 17 required by Gradle
         uses: actions/setup-java@v4
